---
- block:

  - name: "Create azure directory with path {{azure_folder}}"
    file:
      path: "{{azure_folder}}"
      state: directory
      owner: "{{ user }}"
      group: "{{ group }}"
      mode: 0755

  - name: Create Service Principal
    template:
      src: credentials.j2
      dest: "{{azure_folder}}/credentials"
      owner: "{{ user }}"
      group: "{{ group }}"
      mode: 0755


